name: Build project

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

env:
  MAVEN_OPTS: >-
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.http.retryhandler.count=5
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=240

# Cancel running jobs when a new push happens to the same branch as otherwise it will
# tie up too many resources without providing much value.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Linux
  build-linux-x86_64:
    strategy:
      matrix:
        arch: [ ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: zulu

      - name: Configuring Linux Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make perl

      - name: Build netty-tcnative
        run: ./mvnw clean package

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: build-jars
          path: |
            **/target/*.jar

      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: build-target
          path: |
            **/target/surefire-reports/
            **/hs_err*.log

  # Windows
  build-windows-x86_64:
    strategy:
      matrix:
        arch: [ windows-2025, windows11-arm ]
    runs-on: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: zulu

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Configuring Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86_amd64

      - name: Install tools
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install ninja nasm

      # Cache .m2/repository
      - uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ~/.m2/repository
          key: build-windows-m2-repository-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            build-windows-m2-repository-cache-

      - name: Build netty-tcnative
        run: ./mvnw.cmd clean package

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: build-windows-jars
          path: |
            **/target/*.jar

      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: build-windows-target
          path: |
            **/target/surefire-reports/
            **/hs_err*.log